version: "3.9"

services:
    php:
        container_name: dc-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
            - ./docker/supervisor.conf:/etc/supervisor/conf.d/server.conf:ro
        networks:
            - app-network
        ports:
            - ${APP_PORT}:8092
            - ${DEV_SERVER_PORT}:5173
        restart: on-failure
        depends_on:
            - redis
            - mariadb

    mariadb:
        container_name: dc-mariadb
        image: mariadb:10.11.2
        volumes:
            - app-database-volume:/var/lib/mysql
            - ./docker/database:/docker-entrypoint-initdb.d:ro
            - ./docker/database/conf:/etc/mysql/conf.d:ro
        networks:
            - app-network
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
        ports:
            - ${DB_PORT}:3306
        restart: always
        healthcheck:
            test: [ "CMD", "mariadb-admin", "--protocol", "tcp" ,"ping" ]
            timeout: 3m
            interval: 10s
            retries: 10

    redis:
        container_name: dc-redis
        image: redis:7.0.9
        ports:
            - ${REDIS_PORT}:6379
        restart: always
        volumes:
            - app-redis-volume:/data
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mailhog:
        container_name: dc-mailhog
        image: jcalonso/mailhog
        ports:
            - ${MAIL_PORT}:1025
            - ${MAILHOG_HTTP_PORT}:8025
        restart: always
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
volumes:
    app-database-volume:
        driver: local
    app-redis-volume:
        driver: local
